name:                minds
version:             0.1.0.0
github:              "githubuser/minds"
license:             BSD3
author:              "Tarık Özkanlı"
maintainer:          "tozkanli2023@gmail.com"
copyright:           "2021 Tarık Özkanlı"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/minds#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

executables:
  minds-exe:
    main:                Main.hs
    source-dirs:
    - app
    - app/handlers
    - app/routes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minds
    - scotty

tests:
  minds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minds
    - hspec
    - QuickCheck
